sayiBir = input ("Lütfen Uzerinde Islem Yapmak Icin Bir Deger Giriniz.")
sayiIki = input ("Lütfen Uzerinde Islem Yapmak Icin Ikinci Bir Deger Giriniz")
sayiTop =int(sayiBir)+int(sayiIki)
print("Yazdiginiz Degerlerin Toplama Degeri: "+str(sayiTop))
sayiFark =int(sayiIki)-int(sayiBir)
print("Yazdiginiz Degerlerin Fark Degeri: "+str(sayiFark))
sayiCarpim =int(sayiBir)*int(sayiIki)
print("Yazdiginiz Degerlerin Carpim Degeri: "+str(sayiCarpim))
sayiBolum =int(sayiBir)/int(sayiIki)
print("Yazdiginiz Degerlerin Bolum Degeri: "+str(sayiBolum))
print("Baska Hesaplamami Istediginiz Degerler Varsa Hesaplamaktan Memnuniyet Duyarim")